**Import numpy as np**

In [4]:
import numpy as np

**Create an array of 10 zeros**

In [5]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.zeros(10,dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

**Create an array of 10 ones**

In [7]:
one=np.ones((10))
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [8]:
five=np.array([5]*10)
five

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Create an array of the integers from 10 to 50**

New 

In [9]:
range =np.arange(10,50)
range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
print(np.arange(10, 51, 2))


# another method
a = np.arange(10, 51)

a[ a % 2 == 0]

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create an array of all the even integers from 10 to 50**

In [11]:
evenRange=np.arange(10,50,2)


In [12]:
evenRange

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

**Create a 3x4 matrix with numbers ranging from 0 to 12**

In [13]:
new_array=np.arange(0,12).reshape(3,4)

In [14]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Create a 3x3 identity matrix**

In [15]:
identity=np.array([1,0,0,0,1,0,0,0,1])

In [16]:
identity.reshape(3,3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Use Numpy to generate a random number between 0 and 1**

Note: output may differ from yours output

In [17]:
# new method
print(np.random.random())

#
np.random.rand(1)[0]

0.35167277295492116


0.8315661145036469

**Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution**

Note: output may differ from yours output

In [18]:
np.random.standard_normal(25).std()



np.random.randn(25).std()

0.9158267587311252

**Create an (10x10)array having numbers from 0.01 to 1 increasing by 0.01**

In [19]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#Numpy Indexing and Slicing


In [20]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**extract array**

[
  [12,13,14],

  [17,18,19],

  [22,23,24]
]

In [21]:
ar[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

**extract array**

[
  [14, 13, 12],

  [19, 18, 17],

  [24, 23, 22]
]

In [22]:
ar[2:, 3:0:-1]

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

**extract array**

[
  [24, 23, 22],

  [19, 18, 17],

  [14, 13, 12],  
]

In [23]:
ar[4:1:-1, 3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

#Split Concatinate

In [24]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

**Split array to generate 3 arrays with content**

[2,3,4]

[5, 6]

[]

[7,8,9]

In [28]:
np.split(ar,[3,5,5])

[array([2, 3, 4]), array([5, 6]), array([], dtype=int64), array([7, 8, 9])]

In [29]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

**2D**

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

**Concatinate array to create new array with content**

[
  [1,2,3],

  [4,5,6],
  
  [7,8,9]
]

In [30]:
np.vstack([a,b, b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [31]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

**Concatinate array to create new array with content**

[

  [1,2,3, 7,8,9, 10],

  [4,5,6, 11, 12, 13, 14]
  
]

In [32]:
np.hstack([a,b])

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

#Broadcasting and Indexing

below array is created using random values so your output may differ. 

In [ ]:
ar = np.round(np.random.rand(10)*10)
ar

array([ 9.,  8.,  9., 10.,  6.,  6.,  8.,  4.,  5.,  5.])

**create new array containing all numbers which are smaller than 10 in ar**

In [33]:
ar<10

array([ True,  True,  True,  True,  True,  True,  True,  True])

**create new array containing all numbers which are in range [3, 11] in ar**

In [39]:
ar[(ar>=3)&(ar<=11)]

array([3, 4, 5, 6, 7, 8, 9])

**count how many numbers are minimum in ar**

example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [40]:
arr = np.round(np.random.rand(10)*10)
arr

array([5., 3., 7., 0., 2., 1., 8., 2., 4., 4.])

In [41]:
arr[ arr == arr.min() ].size

1

**Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5**

In [43]:
a=np.ones(15)*2
b=np.ones(5)*-5

np.concatenate([a,b])

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2., -5., -5., -5., -5., -5.])

In [44]:
mat = np.round(np.random.rand(50)*100).reshape(5,10)
mat

array([[ 6.,  6., 22., 26., 90., 18., 47., 83., 28., 49.],
       [62., 53., 25., 79., 97., 37., 64., 82., 52., 51.],
       [90., 64., 65., 48., 50.,  6., 70., 55., 77., 23.],
       [47., 87., 57., 52., 95., 95., 72., 35., 78., 90.],
       [56., 73., 21., 73., 44., 31., 82., 97., 49.,  4.]])

**Sum min max of all elements of matrix**

In [35]:
mat = np.array(
    [[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]]
)
mat

array([[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]])

In [37]:
max=mat.max()
min=mat.min()
sum=max-min

In [45]:
print(min)
print(max)
print(sum)

1.0
99.0
98.0


**Standard deviation of mat**

In [46]:
mat.std()

26.599857142473528

28.664654192925475

**Sum of all columns of mat**

In [47]:
mat.sum(axis=0)

array([261., 283., 190., 278., 376., 187., 335., 352., 284., 217.])

In [48]:
ar = np.array([
               [1,2,3,4],
               [10,10,10,10]
])

In [49]:
ar.sum(axis=1)

array([10, 40])

**create array of dimension same as arr using arr.shape variable**

In [50]:
arr = np.arange(100).reshape(4,5,5)
dim = arr.shape

In [51]:
dim = arr.shape

In [52]:
arr2 = np.arange(arr.size).reshape(arr.shape)
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])